eshop/about/urls.py
# файл about/urls.py
from django.urls import path

from . import views

app_name = 'about'
urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

eshop/eshop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

eshop/posts/urls.py
from django.urls import path, re_path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    re_path(r'^(.*)/(?P<post_slug>[-\w]+).html',
            views.post_detail, name='post_detail'),
    path("create/category", views.group_create, name="group_create"),
    path("create/product/<str:product_model>/", views.post_create, name="post_create"),
    path("posts/<slug:slug>/edit/", views.post_edit, name="post_edit"),
    path("group/<slug:slug>/edit/", views.group_edit, name="group_edit"),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("profile/<str:username>/", views.profile, name="profile"),

    re_path(r'^(?P<group_slug>.+)/$', views.group_posts, name="group_list"),    
]

eshop/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

from .constants import *

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200, verbose_name='Категория',
        help_text='Название категории'
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Идентификатор',
        help_text='Название идентификатора'
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Текст описания'
    )
    parent = models.ForeignKey(
        'self', null=True, blank=True, related_name='subcategories', on_delete=models.CASCADE
    )

    def get_ancestors(self):
        ancestors = []
        category = self
        while category is not None:
            ancestors.append(category)
            category = category.parent
        return ancestors[::-1]

    def get_ancestors_slugs(self):
        ancestors = self.get_ancestors()
        slugs = [ancestor.slug for ancestor in ancestors]
        return "/".join(slugs)

    def get_ancestors_urls(category):
        ancestors = category.get_ancestors()
        urls = []
        for ancestor in ancestors:
            url = reverse('posts:group_list', args=[ancestor.get_full_path()])
            urls.append(url)
        return urls

    def get_full_path(category):
        path = category.slug
        parent = category.parent
        while parent:
            path = parent.slug + '/' + path
            parent = parent.parent
        return path

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Brand(models.Model):
    name = models.CharField(
        max_length=100, verbose_name='Бренд',
        help_text='Бренд',
        default='Без бренда'
    )
    slug = models.CharField(
        max_length=255,
        unique=True,
        verbose_name='Идентификатор',
        help_text='Название идентификатора'
    )

    def __str__(self):
        return self.name[:15]
    
    class Meta:
        verbose_name = 'Бренд'
        verbose_name_plural = 'Бренды'


class Post(models.Model):
    title = models.CharField(
        max_length=255, verbose_name='Товар',
        help_text='Название товара',
        blank=False, null=False
    )
    slug = models.CharField(
        max_length=255,
        unique=True,
        verbose_name='Идентификатор',
        help_text='Название идентификатора'
    )
    text = models.TextField(
        verbose_name='Описание товара',
        help_text='Описание товара',
        blank=False, null=False
    )
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        help_text='Имя автора'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        verbose_name='Категория',
        help_text='Категория, к которой будет относиться товар',
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Поле для загрузки картинки',

    )
    price = models.DecimalField(
        'Цена',
        help_text='Поле для цены',
        max_digits=10,
        decimal_places=2
    )
    brand = models.ForeignKey(
        Brand,
        on_delete=models.PROTECT,
        max_length=100,
        verbose_name='Бренд',
        help_text='Бренд',
        default='без бренда',
    )
    color = models.CharField(
        max_length=100,
        verbose_name='Цвет',
        help_text='Цвет',
        choices=COLORS,
        default='нет',
        blank=True, null=True,
    )

    def __str__(self):
        return self.title

    class Meta:
        abstract = True


class Szu(Post):
    fast_charge = models.BooleanField(default='False')
    amper = models.FloatField(choices=AMPERS)
    charger_type = models.CharField(choices=CHARGER_TYPES, max_length=20)
    usb_outputs = models.PositiveIntegerField(choices=USB_OUTPUTS)
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'СЗУ'
        verbose_name_plural = 'СЗУ'
    

class SzuUsb(Post):
    fast_charge = models.BooleanField(default='False')
    amper = models.FloatField(choices=AMPERS)
    usb_outputs = models.PositiveIntegerField(choices=USB_OUTPUTS)
    
    def __str__(self):
        return self.title    
    
    class Meta:
        verbose_name = 'СЗУ-USB'
        verbose_name_plural = 'СЗУ-USB'


class Headphones(Post):
    microphone = models.BooleanField()
    
    def __str__(self):
        return self.title    
    
    class Meta:
        verbose_name = 'Наушники'
        verbose_name_plural = 'Наушники'        


class Azu(Post):
    fast_charge = models.BooleanField(default='False')
    amper = models.FloatField(choices=AMPERS)
    charger_type = models.CharField(choices=CHARGER_TYPES, max_length=20)
    
    def __str__(self):
        return self.title    
    
    class Meta:
        verbose_name = 'АЗУ'
        verbose_name_plural = 'АЗУ' 


class AzuUsb(Post):
    amper = models.FloatField(choices=AMPERS)
    usb_outputs = models.PositiveIntegerField(choices=USB_OUTPUTS)
    fast_charge = models.BooleanField(default='False')
    
    def __str__(self):
        return self.title    
    
    class Meta:
        verbose_name = 'АЗУ-USB'
        verbose_name_plural = 'АЗУ-USB' 


class DataCabel(Post):
    amper = models.FloatField(choices=AMPERS, null=True, blank=True)
    length = models.FloatField(choices=CABEL_LENGTH, default=1)
    charger_type = models.CharField(choices=CHARGER_TYPES, max_length=20)

    def __str__(self):
        return self.title    
    
    class Meta:
        verbose_name = 'Дата-кабель'
        verbose_name_plural = 'Дата-кабели'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
        help_text='Имя подписчика',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
        help_text='Имя автора'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name="unique_followers")
        ]

    def __str__(self):
        return SUBSCRIPTION.format(
            user=self.user.username, author=self.author.username
        )

eshop/posts/forms.py
from django import forms

from .models import Group, Szu, SzuUsb


class SzuForm(forms.ModelForm):
    class Meta:
        model = Szu
        fields = ('title', 'text', 'group', 'image', 'price')


class SzuUsbForm(forms.ModelForm):
    fast_charge = forms.BooleanField(required=False)
    class Meta:
        model = SzuUsb
        exclude = ('slug', 'author')
        


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('title', 'description', 'parent')

eshop/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.utils.text import slugify
from django.shortcuts import render, get_object_or_404, redirect, reverse
from pytils.translit import slugify
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.forms.models import modelform_factory

from .forms import SzuForm, GroupForm, SzuUsbForm
from .models import Post, Group, User, Follow
from .settings import POSTS_PER_PAGE
from .constants import PRODUCT_SPECS


def page_obj(request, posts):
    return Paginator(posts, POSTS_PER_PAGE).get_page(request.GET.get('page'))


def index(request):
    child_objects = []
    for model in Post.__subclasses__():
        child_objects.extend(model.objects.all())
    return render(request, 'posts/index.html', {
        'page_obj': page_obj(request, child_objects),
    })


def process_subcategories(category, subcategory_list):
    subcategories = category.subcategories.all()
    subcategory_list.append(category)
    for subcategory in subcategories:
        process_subcategories(subcategory, subcategory_list)


def group_posts(request, group_slug):
    group_slug = group_slug.split('/')[-1]
    group = get_object_or_404(Group, slug=group_slug)

    subcategory_list = []
    process_subcategories(group, subcategory_list)

    child_objects = []
    for model in Post.__subclasses__():
        child_objects.extend(model.objects.filter(group__in=subcategory_list))

    return render(request, 'posts/group_list.html', {
        'page_obj': page_obj(request, child_objects),
        'group': group,
    })

def profile(request, username):
    author = get_object_or_404(User, username=username)
    child_objects = []
    for model in Post.__subclasses__():
        child_objects.extend(model.objects.filter(author=author))
    return render(request, 'posts/profile.html', {
        'page_obj': page_obj(request, child_objects),
        'author': author,
        'following':
            request.user != author
            and request.user.is_authenticated
            and Follow.objects.filter(
                user=request.user, author=author
        ).exists(),
    })


def post_detail(request, post_slug):
    for model in Post.__subclasses__():
        try:
            obj = model.objects.get(slug=post_slug)
            return render(request, 'posts/post_detail.html', {'post': obj, 'PRODUCT_SPECS': PRODUCT_SPECS})
        except model.DoesNotExist:
            continue
    raise Http404("Post not found")


@login_required
def post_create(request, product_model):

    PRODUCT_MODELS = {
        'zaryadki-s-kabelem': SzuForm,
        'szu': SzuUsbForm,
    }
    form = PRODUCT_MODELS[product_model](request.POST or None, files=request.FILES or None)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {
            'form': form,
            'product_model': product_model,
        })
    post = form.save(commit=False)
    post.author = request.user
    post.slug = slugify(post.title)
    post.save()
    return redirect('posts:profile', request.user)


@login_required
def post_edit(request, slug):
    for model in Post.__subclasses__():
        try:
            post = model.objects.get(slug=slug)
        except model.DoesNotExist:
            continue
    if post.author != request.user:
        return redirect('posts:post_detail', post_slug=slug)
    form_class = modelform_factory(post.__class__, exclude=[])
    form = form_class(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {
            'form': form,
            'post': post,
        })
    # post.slug = slugify(post.title)
    form.save()
    return redirect(reverse('posts:post_detail', args=[post.group.get_ancestors_slugs, post.slug]))


@login_required
def group_create(request):
    form = GroupForm(request.POST or None, files=request.FILES or None)
    if not form.is_valid():
        return render(request, 'posts/create_group.html', {
            'form': form,
        })
    group = form.save(commit=False)
    group.slug = slugify(group.title)
    group.save()
    return redirect('posts:profile', request.user)


@login_required
def group_edit(request, slug):
    group = get_object_or_404(Group, slug=slug)
    form = GroupForm(
        request.POST or None,
        files=request.FILES or None,
        instance=group)
    if not form.is_valid():
        return render(request, 'posts/create_group.html', {
            'form': form,
            'group': group,
        })
    group.slug = slugify(group.title)
    form.save()
    return redirect('posts:group_list', slug=slug)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    return render(request, 'posts/follow.html', {
        'page_obj': page_obj(request, posts),
    })


@login_required
def profile_follow(request, username):
    if request.user.username != username:
        Follow.objects.get_or_create(
            user=request.user,
            author=get_object_or_404(User, username=username)
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    get_object_or_404(
        Follow,
        user=request.user,
        author__username=username
    ).delete()
    return redirect('posts:profile', username=username)

eshop/templates/posts/create_group.html
{% extends "base.html" %}
{% block title %}
  {% if group %}Редактировать категорию{% else %}Создать категорию{% endif %}
{% endblock %}
{% block content %}
<h1>Создать категорию</h1>
  {% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-12 p-5">
      <div class="card">
        <div class="card-header">
          {% if group %}Редактировать категорию{% else %}Новая категория{% endif %}
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data"
            action="
            {% if group %}
              {% url 'posts:group_edit' group.slug %}
            {% else %}
              {% url 'posts:group_create' %}
            {% endif %}
            "
          >
            {% csrf_token %}
            {% if form.errors %}
              {% for error in form.field_errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
              {% for error in form.non_field_errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
            {% endif %}
            {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
                </label>
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                {% endif %}
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if group %}Сохранить{% else %}Добавить{% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

eshop/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
  {% if post %}Редактировать товар{% else %}Создать товар{% endif %}
{% endblock %}
{% block content %}
<h3>Создать товар</h3>
  {% load user_filters %}
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          {% if post %}Редактировать товар{% else %}Новый товар{% endif %}
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data"
            action="
            {% if post %}
              {% url 'posts:post_edit' post.slug %}
            {% else %}
              {% url 'posts:post_create' product_model=product_model %}
            {% endif %}
            "
          >
            {% csrf_token %}
            {% if form.errors %}
              {% for error in form.field_errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
              {% for error in form.non_field_errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
            {% endif %}
            {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
                </label>
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                {% endif %}
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if post %}Сохранить{% else %}Добавить{% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

eshop/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Последние записи избранных авторов{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' with follow=True %}
  <h1>Последние записи избранных авторов</h1>
  {% load cache %}
  {% cache 20 follow_page page_obj.number %}
    {% for post in page_obj %}
      {% include 'posts/includes/post.html' %}
      {% if not forloop.last %}<hr />{% endif %}
    {% endfor %}
  {% endcache %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

eshop/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи группы "{{ group.title }}"{% endblock %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description|linebreaksbr }}</p>
  {% if post.author == user %}
    <a class="btn btn-primary"
       href="{% url 'posts:group_edit' group.slug %}">редактировать категорию</a>
  {% endif %}

  {% comment %} <nav class="nav nav-tabs">
    {% for subcategory in group.subcategories.all %}
      <a href="{% url 'posts:group_list' subcategory.get_full_path %}"
         class="btn">{{ subcategory.title }}</a>&nbsp;
    {% endfor %}
  </nav>   {% endcomment %}
  <ul class="nav nav-underline">
    {% for subcategory in group.subcategories.all %}
    <li class="nav-item">
      <a class="nav-link" aria-current="page" href="{% url 'posts:group_list' subcategory.get_full_path %}">{{ subcategory.title }}</a>
    </li>
    {% endfor %}
  </ul>
  <div class="row">
    {% for post in page_obj %}
      <div class='col-3 mb-3'>{% include 'posts/includes/post.html' with hide_group=True %}</div>
    {% endfor %}
    {% comment %} {% load user_filters %}
    {% for subcategory in group|recursive_subcategories %}
      {% for post in subcategory.posts.all %}
        <div class='col-3 mb-3'>{% include 'posts/includes/post.html' with hide_group=True %}</div>
      {% endfor %}
    {% endfor %} {% endcomment %}
  </div>
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

eshop/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  {% comment %} {% include 'posts/includes/switcher.html' with index=True %} {% endcomment %}
  <h1>Последние поступления</h1>
  {% comment %} {% load cache %} {% endcomment %}
  {% comment %} {% cache 20 index_page page_obj.number %} {% endcomment %}

    <div class="row">
      {% for post in page_obj %}
        <div class='col-3 mb-3'>{% include 'posts/includes/post.html' %}</div>
        {% comment %} {% if not forloop.last %}<hr />{% endif %} {% endcomment %}
      {% endfor %}
    </div>

{% comment %} {% endcache %} {% endcomment %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

eshop/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}{{ post.text|slice:"0:100" }}{% endblock %}
{% block content %}
  <div class="row">
    <article class="col-12 col-md-9">
      <h2>{{ post.title|linebreaksbr }}</h2>
      {% thumbnail post.image "600x400" as im %}
        <div class="image-container text-center">
          <img class="card-img my-2"
               src="{{ im.url }}"
               style="width: auto;
                      max-height: 300px"
               alt="{{ post.title }}">
        </div>
      {% endthumbnail %}
      <br>
      <p>{{ post.text|linebreaksbr }}</p>
      {% if post.author == user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.slug %}">редактировать пост</a>
      {% endif %}
      <div class='col-12'>
        <br>
        <br>
        <h5>Характеристики:</h5>
        <table class="table table-stripe">
          <tbody>
            <tr>
              <td>Бренд</td>
              <td>{{ post.brand }}</td>
            </tr>
            <tr>
              <td>Цвет</td>
              <td>{{ post.color }}</td>
            </tr>
            {% for spec, value in PRODUCT_SPECS.items %}
              {% if post|attr:spec %}
                <tr>
                  <td>{{ value }}</td>
                  <td>{{ post|attr:spec }}</td>
                </tr>
            {% endif %}
          {% endfor %}
        </tbody>
      </table>
    </div>
  </article>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      {% if post.group %}
        <li class="list-group-item">
          Категория:
          <a href="{% url 'posts:group_list' post.group.get_ancestors_slugs %}">{{ post.group.title }}</a>
        </li>
      {% endif %}
      <li class="list-group-item">
        <h3>{{ post.price }} Р.</h3>
      </li>
    </ul>
  </aside>
</div>
{% endblock %}

eshop/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}
{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.username }} ({{ author.get_full_name }})</h1>
    <h5>Постов: {{ child_objects }}</h5>
    <h5>Подписок: {{ author.follower.count }}</h5>
    <h5>Подписчиков: {{ author.following.count }}</h5>
    <h5>Комментариев: {{ author.comments.count }}</h5>
    {% if user != author and user.is_authenticated %}
      {% if following %}
        <a class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}"
            role="button">Отписаться</a>
      {% else %}
        <a class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}"
            role="button">Подписаться</a>
      {% endif %}
    {% endif %}
    {% load cache %}
    {% cache 20 profile_page page_obj.number %}
    <div class="row">
      {% for post in page_obj %}
      <div class='col-12 mb-3'>{% include 'posts/includes/post.html' %}</div>
        {% if not forloop.last %}<hr />{% endif %}
      {% endfor %}
    </div> 
    {% endcache %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}