eshop/about/urls.py
# файл about/urls.py
from django.urls import path

from . import views

app_name = 'about'
urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

eshop/eshop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

eshop/posts/urls.py
from django.urls import path, re_path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    re_path(r'^(.*)/(?P<post_slug>[-\w]+).html',
            views.post_detail, name='post_detail'),
    path("create/category", views.group_create, name="group_create"),
    path("create/product/<str:product_model>/", views.post_create, name="post_create"),
    path("posts/<slug:slug>/edit/", views.post_edit, name="post_edit"),
    path("group/<slug:slug>/edit/", views.group_edit, name="group_edit"),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("profile/<str:username>/", views.profile, name="profile"),

    re_path(r'^(?P<group_slug>.+)/$', views.group_posts, name="group_list"),    
]

eshop/templates/includes/footer.html
<p>
    © {{ year }} Copyright <span style="color:red">Mobi</span>Smartfon
</p>

eshop/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <!-- <img src="{% static 'img/logo.png' %}"
      width="30"
      height="30"
      class="d-inline-block align-top"
      alt=""> -->
      <b><span style="color:red">Mobi</span>Smartfon</b>
    </a>
    <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'about:author' %}active{% endif %}"
             href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}"
             href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle {% if view_name == 'posts:post_create' %}active{% endif %}"
               id="dropdownMenuLink"
               role="button"
               data-bs-toggle="dropdown"
               aria-expanded="false"
               href="#">Новый товар</a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <li>
                <a class="dropdown-item"
                   href="{% url 'posts:post_create' product_model='szu' %}">Зарядное устройство</a>
              </li>
              <li>
                <a class="dropdown-item"
                   href="{% url 'posts:post_create' product_model='product2' %}">Товар 2</a>
              </li>
              <li>
                <a class="dropdown-item"
                   href="{% url 'posts:post_create' product_model='product3' %}">Товар 3</a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'posts:group_create' %}active{% endif %}"
               href="{% url 'posts:group_create' %}">Новая категория</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name == 'users:password_change_form' %}active{% endif %}"
               href="{% url 'users:password_change_form' %}">Изменить пароль</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name == 'users:logout' %}active{% endif %}"
               href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li>
            Пользователь: <a href="{% url 'posts:profile' user.username %}">{{ user.username }}</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name == 'users:login' %}active{% endif %}"
               href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name == 'users:signup' %}active{% endif %}"
               href="{% url 'users:signup' %}">Регистрация</a>
          </li>
        {% endif %}
      {% endwith %}
    </ul>
  </div>
</nav>

eshop/templates/includes/side_menu.html
{% comment %} {% load cache %} {% endcomment %}
<div class="nav flex-column nav-pills border" id="v-pills-tab" role="tablist" aria-orientation="vertical">
    {% comment %} {% cache 300 side_menu_cache %}  {# Кэшируем на 5 минут (300 секунд) #} {% endcomment %}
    {% for group in groups %}
    <a href="{% url 'posts:group_list' group.get_full_path %}" class="nav-link link-opacity-90 nav-underline" id="v-pills-home-tab" data-toggle="pill" role="tab" aria-controls="v-pills-home" aria-selected="false">{{ group.title }}</a>
    {% endfor %}
    {% comment %} {% endcache %} {% endcomment %}
</div>